language: go
go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"

services:
  - mysql
  - postgresql

install: true

addons:
  postgresql: "9.6"
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server

dist: trusty

sudo: required

env:
  - GO111MODULE=on

git:
  depth: 1

go_import_path: github.com/bigpigeon/toyorm



before_install:
  - go get -t -v ./...
  - go get -u github.com/client9/misspell/cmd/misspell
  - mysql -e 'CREATE DATABASE toyorm DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - mysql -e 'CREATE DATABASE toyorm1 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - mysql -e 'CREATE DATABASE toyorm2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - psql -c 'CREATE DATABASE toyorm;' -U postgres;
  - psql -c 'CREATE DATABASE toyorm1;' -U postgres;
  - psql -c 'CREATE DATABASE toyorm2;' -U postgres;
  - go vet .
  - diff=$(gofmt -s -d .);if [ -n "$diff" ]; then exit 1; fi;
  - misspell -error .


script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic $(go list ./...|grep -v /examples/)

after_success:
  - bash <(curl -s https://codecov.io/bash)
