// Code generated by "stringer -type AssociationType"; DO NOT EDIT.

package toyorm

import "fmt"

const _AssociationType_name = "JoinWithBelongToWithOneToOneWithOneToManyWithAssociationTypeEnd"

var _AssociationType_index = [...]uint8{0, 8, 20, 32, 45, 63}

func (i AssociationType) String() string {
	if i < 0 || i >= AssociationType(len(_AssociationType_index)-1) {
		return fmt.Sprintf("AssociationType(%d)", i)
	}
	return _AssociationType_name[_AssociationType_index[i]:_AssociationType_index[i+1]]
}
